<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FactoryConnect.Persistence.SqlServer</RootNamespace>
    <AssemblyName>FactoryConnect.Persistence.SqlServer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Sql\001_InitialObservationIngestion.sql"
                      LogicalName="FactoryConnect.Persistence.SqlServer.Sql.001_InitialObservationIngestion.sql" />
    <EmbeddedResource Include="Sql\002_DurableMetricAggregation.sql"
                      LogicalName="FactoryConnect.Persistence.SqlServer.Sql.002_DurableMetricAggregation.sql" />
    <EmbeddedResource Include="Sql\003_BindMetricInputFactMachine.sql"
                      LogicalName="FactoryConnect.Persistence.SqlServer.Sql.003_BindMetricInputFactMachine.sql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FactoryConnect.Abstractions/FactoryConnect.Abstractions.csproj" />
    <ProjectReference Include="../FactoryConnect.Persistence/FactoryConnect.Persistence.csproj" />
  </ItemGroup>
</Project>
