<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>FactoryConnect.Api</RootNamespace>
    <AssemblyName>FactoryConnect.Api</AssemblyName>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiDocumentsDirectory>$(BaseIntermediateOutputPath)openapi</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--document-name v1 --file-name factoryconnect-api-v1</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" />
    <ProjectReference Include="../FactoryConnect.Abstractions/FactoryConnect.Abstractions.csproj" />
    <ProjectReference Include="../FactoryConnect.Core/FactoryConnect.Core.csproj" />
    <ProjectReference Include="../FactoryConnect.Infrastructure/FactoryConnect.Infrastructure.csproj" />
    <ProjectReference Include="../FactoryConnect.Persistence/FactoryConnect.Persistence.csproj" />
  </ItemGroup>
</Project>
