<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FactoryConnect.Core</RootNamespace>
    <AssemblyName>FactoryConnect.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FactoryConnect.Abstractions/FactoryConnect.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FactoryConnect.Core.Tests" />
  </ItemGroup>
</Project>
