<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FactoryConnect.Protocols.MTConnect</RootNamespace>
    <AssemblyName>FactoryConnect.Protocols.MTConnect</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FactoryConnect.Abstractions/FactoryConnect.Abstractions.csproj" />
    <InternalsVisibleTo Include="FactoryConnect.Protocols.MTConnect.Tests" />
  </ItemGroup>
</Project>
